#!/bin/bash
# `set -e`` errors out (cancels commit) if any command returns non-zero
set -e
GITHOOK_COMMITMSG_HEAD="$(head -1 $1)" GITHOOK_CWD=`pwd` GITHOOK_SCRIPT=$0 \
    deno run -A --unstable Taskfile.ts git-hook-prepare-commit-msg
