#!/bin/bash
set -e    # cancels commit if Taskfile.ts git-hook-prepare-commit-msg returns non-zero
GITHOOK_COMMITMSG_HEAD="$(head -1 $1)" GITHOOK_CWD=`pwd` GITHOOK_SCRIPT=$0 \
  deno run -A --unstable Taskfile.ts git-hook-prepare-commit-msg