@startuml IE
  hide circle
  skinparam linetype ortho
  skinparam roundcorner 20
  skinparam class {
    BackgroundColor White
    ArrowColor Silver
    BorderColor Silver
    FontColor Black
    FontSize 12
  }

  entity "execution_context" as execution_context {
    * **code**: INTEGER
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "graph_nature" as graph_nature {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "boundary_nature" as boundary_nature {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "asset_risk_type" as asset_risk_type {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "host" as host {
    * **host_id**: INTEGER
    --
    * host_name: TEXT
      created_at: DATETIME
  }

  entity "graph" as graph {
    * **graph_id**: INTEGER
    --
    * graph_nature_id: TEXT <<ENUM(graph_nature)>>
    * name: TEXT
      description: TEXT
      created_at: DATETIME
  }

  entity "boundary" as boundary {
    * **boundary_id**: INTEGER
    --
      parent_boundary_id: INTEGER <<SELF>>
    * graph_id: INTEGER <<FK(graph)>>
    * boundary_nature_id: TEXT <<ENUM(boundary_nature)>>
    * name: TEXT
      created_at: DATETIME
  }

  entity "host_boundary" as host_boundary {
    * **host_boundary_id**: INTEGER
    --
    * host_id: INTEGER <<FK(host)>>
    * boundary_id: INTEGER <<FK(boundary)>>
      created_at: DATETIME
  }

  entity "raci_matrix" as raci_matrix {
    * **raci_matrix_id**: INTEGER
    --
    * asset: TEXT
    * responsible: TEXT
    * accountable: TEXT
    * consulted: TEXT
    * informed: TEXT
      created_at: DATETIME
  }

  entity "asset_risk" as asset_risk {
    * **asset_risk_id**: INTEGER
    --
    * asset_risk_type_id: TEXT <<ENUM(asset_risk_type)>>
    * asset: TEXT
    * threat_event: TEXT
    * relevance: TEXT
    * likelihood: TEXT
    * impact: TEXT
      created_at: DATETIME
  }

  graph_nature |o..o| graph
  boundary |o..o{ boundary
  graph |o..o{ boundary
  boundary_nature |o..o| boundary
  host |o..o{ host_boundary
  boundary |o..o{ host_boundary
  asset_risk_type |o..o| asset_risk
@enduml