@startuml models
  hide circle
  skinparam linetype ortho
  skinparam roundcorner 20
  skinparam class {
    BackgroundColor White
    ArrowColor Silver
    BorderColor Silver
    FontColor Black
    FontSize 12
  }

  entity "execution_context" as execution_context {
    * **code**: INTEGER
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "graph_nature" as graph_nature {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "boundary_nature" as boundary_nature {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "asset_risk_type" as asset_risk_type {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "security_incident_role" as security_incident_role {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "host" as host {
    * **host_id**: INTEGER
    --
    * host_name: TEXT
      created_at: DATETIME
  }

  entity "graph" as graph {
    * **graph_id**: INTEGER
    --
    * graph_nature_id: TEXT <<ENUM(graph_nature)>>
    * name: TEXT
      description: TEXT
      created_at: DATETIME
  }

  entity "boundary" as boundary {
    * **boundary_id**: INTEGER
    --
      parent_boundary_id: INTEGER <<SELF>>
    * graph_id: INTEGER <<FK(graph)>>
    * boundary_nature_id: TEXT <<ENUM(boundary_nature)>>
    * name: TEXT
      created_at: DATETIME
  }

  entity "host_boundary" as host_boundary {
    * **host_boundary_id**: INTEGER
    --
    * host_id: INTEGER <<FK(host)>>
    * boundary_id: INTEGER <<FK(boundary)>>
      created_at: DATETIME
  }

  entity "raci_matrix" as raci_matrix {
    * **raci_matrix_id**: INTEGER
    --
    * asset: TEXT
    * responsible: TEXT
    * accountable: TEXT
    * consulted: TEXT
    * informed: TEXT
      created_at: DATETIME
  }

  entity "asset_risk" as asset_risk {
    * **asset_risk_id**: INTEGER
    --
    * asset_risk_type_id: TEXT <<ENUM(asset_risk_type)>>
    * asset: TEXT
    * threat_event: TEXT
    * relevance: TEXT
    * likelihood: TEXT
    * impact: TEXT
      created_at: DATETIME
  }

  entity "vulnerability" as vulnerability {
    * **vulnerability_id**: INTEGER
    --
    * short_name: TEXT
    * source: TEXT
    * affected_software: TEXT
    * reference: TEXT
    * status: TEXT
    * patch_availability: TEXT
    * severity: TEXT
    * solutions: TEXT
    * tags: TEXT
    * description: TEXT
      created_at: DATETIME
  }

  entity "threat_source" as threat_source {
    * **threat_source_id**: INTEGER
    --
    * threat_source: TEXT
    * identifier: TEXT
    * threat_source_type: TEXT
    * source_of_information: TEXT
    * capability: TEXT
    * intent: TEXT
    * targeting: TEXT
    * description: TEXT
      created_at: DATETIME
  }

  entity "threat_event" as threat_event {
    * **threat_event_id**: INTEGER
    --
    * threat_event: TEXT
    * identifier: TEXT
    * threat_event_type: INTEGER
    * event_classification: TEXT
    * source_of_information: TEXT
    * description: TEXT
      created_at: DATETIME
  }

  entity "billing" as billing {
    * **billing_id**: INTEGER
    --
    * purpose: TEXT
    * bill_rate: TEXT
    * period: TEXT
    * effective_from_date: DATETIME
    * effective_to_date: TEXT
    * prorate: INTEGER
      created_at: DATETIME
  }

  entity "scheduled_task" as scheduled_task {
    * **scheduled_task_id**: INTEGER
    --
    * description: TEXT
    * task_date: DATETIME
    * reminder_date: DATETIME
    * assigned_to: TEXT
    * reminder_to: TEXT
      created_at: DATETIME
  }

  entity "timesheet" as timesheet {
    * **timesheet_id**: INTEGER
    --
    * time_hour: INTEGER
    * timesheet_summary: TEXT
    * start_time: TEXT
    * end_time: TEXT
      created_at: DATETIME
  }

  entity "certificate" as certificate {
    * **certificate_id**: INTEGER
    --
    * certificate_name: TEXT
    * short_name: TEXT
    * certificate_category: TEXT
    * certificate_type: TEXT
    * certificate_authority: TEXT
    * validity: TEXT
    * expiration_date: DATETIME
    * domain_name: TEXT
    * key_size: INTEGER
    * path: TEXT
      created_at: DATETIME
  }

  entity "device" as device {
    * **device_id**: INTEGER
    --
    * device_name: TEXT
    * short_name: TEXT
    * barcode: TEXT
    * model: TEXT
    * serial_number: TEXT
    * firmware: TEXT
    * data_center: TEXT
    * location: TEXT
    * purpose: TEXT
    * description: TEXT
      created_at: DATETIME
  }

  graph_nature |o..o| graph
  boundary |o..o{ boundary
  graph |o..o{ boundary
  boundary_nature |o..o| boundary
  host |o..o{ host_boundary
  boundary |o..o{ host_boundary
  asset_risk_type |o..o| asset_risk
@enduml