@startuml models
  hide circle
  skinparam linetype ortho
  skinparam roundcorner 20
  skinparam class {
    BackgroundColor White
    ArrowColor Silver
    BorderColor Silver
    FontColor Black
    FontSize 12
  }

  entity "execution_context" as execution_context {
    * **code**: INTEGER
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "graph_nature" as graph_nature {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "boundary_nature" as boundary_nature {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "asset_risk_type" as asset_risk_type {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "organization_role_type" as organization_role_type {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "party_type" as party_type {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "person_type" as person_type {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "contact_type" as contact_type {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "party_relation_type" as party_relation_type {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "record_status" as record_status {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "training_subject" as training_subject {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "status_value" as status_value {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "rating_value" as rating_value {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "contract_type" as contract_type {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "agreement_type" as agreement_type {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "risk_type" as risk_type {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "severity_type" as severity_type {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "priority_type" as priority_type {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "incident_type" as incident_type {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "incident_status" as incident_status {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "incident_category_type" as incident_category_type {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "risk_subject" as risk_subject {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "party_role_type" as party_role_type {
    * **code**: TEXT
    --
    * value: TEXT
      created_at: DATETIME
  }

  entity "host" as host {
    * **host_id**: INTEGER
    --
    * host_name: TEXT
      created_at: DATETIME
  }

  entity "graph" as graph {
    * **graph_id**: INTEGER
    --
    * graph_nature_id: TEXT <<ENUM(graph_nature)>>
    * name: TEXT
      description: TEXT
      created_at: DATETIME
  }

  entity "boundary" as boundary {
    * **boundary_id**: INTEGER
    --
      parent_boundary_id: INTEGER <<SELF>>
    * graph_id: INTEGER <<FK(graph)>>
    * boundary_nature_id: TEXT <<ENUM(boundary_nature)>>
    * name: TEXT
      created_at: DATETIME
  }

  entity "host_boundary" as host_boundary {
    * **host_boundary_id**: INTEGER
    --
    * host_id: INTEGER <<FK(host)>>
    * boundary_id: INTEGER <<FK(boundary)>>
      created_at: DATETIME
  }

  entity "raci_matrix" as raci_matrix {
    * **raci_matrix_id**: INTEGER
    --
    * asset: TEXT
    * responsible: TEXT
    * accountable: TEXT
    * consulted: TEXT
    * informed: TEXT
      created_at: DATETIME
  }

  entity "asset_risk" as asset_risk {
    * **asset_risk_id**: INTEGER
    --
    * asset_risk_type_id: TEXT <<ENUM(asset_risk_type)>>
    * asset: TEXT
    * threat_event: TEXT
    * relevance: TEXT
    * likelihood: TEXT
    * impact: TEXT
      created_at: DATETIME
  }

  entity "vulnerability" as vulnerability {
    * **vulnerability_id**: INTEGER
    --
    * short_name: TEXT
    * source: TEXT
    * affected_software: TEXT
    * reference: TEXT
    * status: TEXT
    * patch_availability: TEXT
    * severity: TEXT
    * solutions: TEXT
    * tags: TEXT
    * description: TEXT
      created_at: DATETIME
  }

  entity "threat_source" as threat_source {
    * **threat_source_id**: INTEGER
    --
    * threat_source: TEXT
    * identifier: TEXT
    * threat_source_type: TEXT
    * source_of_information: TEXT
    * capability: TEXT
    * intent: TEXT
    * targeting: TEXT
    * description: TEXT
      created_at: DATETIME
  }

  entity "threat_event" as threat_event {
    * **threat_event_id**: INTEGER
    --
    * threat_event: TEXT
    * identifier: TEXT
    * threat_event_type: INTEGER
    * event_classification: TEXT
    * source_of_information: TEXT
    * description: TEXT
      created_at: DATETIME
  }

  entity "billing" as billing {
    * **billing_id**: INTEGER
    --
    * purpose: TEXT
    * bill_rate: TEXT
    * period: TEXT
    * effective_from_date: DATETIME
    * effective_to_date: TEXT
    * prorate: INTEGER
      created_at: DATETIME
  }

  entity "scheduled_task" as scheduled_task {
    * **scheduled_task_id**: INTEGER
    --
    * description: TEXT
    * task_date: DATETIME
    * reminder_date: DATETIME
    * assigned_to: TEXT
    * reminder_to: TEXT
      created_at: DATETIME
  }

  entity "timesheet" as timesheet {
    * **timesheet_id**: INTEGER
    --
    * time_hour: INTEGER
    * timesheet_summary: TEXT
    * start_time: TEXT
    * end_time: TEXT
      created_at: DATETIME
  }

  entity "certificate" as certificate {
    * **certificate_id**: INTEGER
    --
    * certificate_name: TEXT
    * short_name: TEXT
    * certificate_category: TEXT
    * certificate_type: TEXT
    * certificate_authority: TEXT
    * validity: TEXT
    * expiration_date: DATETIME
    * domain_name: TEXT
    * key_size: INTEGER
    * path: TEXT
      created_at: DATETIME
  }

  entity "device" as device {
    * **device_id**: INTEGER
    --
    * device_name: TEXT
    * short_name: TEXT
    * barcode: TEXT
    * model: TEXT
    * serial_number: TEXT
    * firmware: TEXT
    * data_center: TEXT
    * location: TEXT
    * purpose: TEXT
    * description: TEXT
      created_at: DATETIME
  }

  entity "party" as party {
    * **party_id**: INTEGER
    --
    * party_type_id: TEXT <<ENUM(party_type)>>
    * party_name: TEXT
    * record_status_id: TEXT <<ENUM(record_status)>>
      created_at: DATETIME
  }

  entity "person" as person {
    * **person_id**: INTEGER
    --
    * party_id: INTEGER <<FK(party)>>
    * person_type_id: TEXT <<ENUM(person_type)>>
    * person_first_name: TEXT
    * person_last_name: TEXT
    * record_status_id: TEXT <<ENUM(record_status)>>
      created_at: DATETIME
  }

  entity "organization" as organization {
    * **organization_id**: INTEGER
    --
    * party_id: INTEGER <<FK(party)>>
    * name: TEXT
    * license: TEXT
    * registration_date: DATE
    * record_status_id: TEXT <<ENUM(record_status)>>
      created_at: DATETIME
  }

  entity "party_relation" as party_relation {
    * **party_relation_id**: INTEGER
    --
    * party_id: INTEGER <<FK(party)>>
    * related_party_id: INTEGER <<FK(party)>>
    * relation_type_id: TEXT <<ENUM(party_relation_type)>>
    * party_role_id: TEXT <<ENUM(party_role_type)>>
    * record_status_id: TEXT <<ENUM(record_status)>>
      created_at: DATETIME
  }

  entity "contact_electronics" as contact_electronics {
    * **contact_electronics_id**: INTEGER
    --
    * contact_type_id: TEXT <<ENUM(contact_type)>>
    * party_id: INTEGER <<FK(party)>>
    * electronics_details: TEXT
    * record_status_id: TEXT <<ENUM(record_status)>>
      created_at: DATETIME
  }

  entity "contact_land" as contact_land {
    * **contact_land_id**: INTEGER
    --
    * contact_type_id: TEXT <<ENUM(contact_type)>>
    * party_id: INTEGER <<FK(party)>>
    * address_line1: TEXT
    * address_line2: TEXT
    * address_zip: TEXT
    * address_city: TEXT
    * address_state: TEXT
    * address_country: TEXT
    * record_status_id: TEXT <<ENUM(record_status)>>
      created_at: DATETIME
  }

  entity "organization_role" as organization_role {
    * **organization_role_id**: INTEGER
    --
    * person_party_id: INTEGER <<FK(party)>>
    * organization_party_id: INTEGER <<FK(party)>>
    * organization_role_type_id: TEXT <<ENUM(organization_role_type)>>
    * record_status_id: TEXT <<ENUM(record_status)>>
      created_at: DATETIME
  }

  entity "rating" as rating {
    * **rating_id**: INTEGER
    --
    * party_id: INTEGER <<FK(party)>>
    * score_id: TEXT <<ENUM(rating_value)>>
    * record_status_id: TEXT <<ENUM(record_status)>>
      created_at: DATETIME
  }

  entity "contract" as contract {
    * **contract_id**: INTEGER
    --
    * party_id: INTEGER <<FK(party)>>
    * contract_type_id: TEXT <<ENUM(contract_type)>>
    * date_contract_signed: DATETIME
    * date_contract_expires: DATETIME
    * date_of_last_review: DATETIME
    * date_of_next_review: DATETIME
    * date_of_contract_review: DATETIME
    * date_of_contract_approval: DATETIME
    * record_status_id: TEXT <<ENUM(record_status)>>
      created_at: DATETIME
  }

  entity "note" as note {
    * **note_id**: INTEGER
    --
    * party_id: INTEGER <<FK(party)>>
    * note: TEXT
    * record_status_id: TEXT <<ENUM(record_status)>>
      created_at: DATETIME
  }

  entity "agreement" as agreement {
    * **agreement_id**: INTEGER
    --
    * party_id: INTEGER <<FK(party)>>
    * agreement_type_id: TEXT <<ENUM(agreement_type)>>
    * signed_status_id: TEXT <<ENUM(status_value)>>
    * document_path: TEXT
    * record_status_id: TEXT <<ENUM(record_status)>>
      created_at: DATETIME
  }

  entity "risk_register" as risk_register {
    * **risk_register_id**: INTEGER
    --
    * description: TEXT
    * risk_subject_id: TEXT <<ENUM(risk_subject)>>
    * risk_type_id: TEXT <<ENUM(risk_type)>>
    * impact_to_the_organization: TEXT
    * rating_likelihood_id: TEXT <<ENUM(rating_value)>>
    * rating_impact_id: TEXT <<ENUM(rating_value)>>
    * rating_overall_risk_id: TEXT <<ENUM(rating_value)>>
    * control_effectivenes_controls_in_place: TEXT
    * control_effectivenes_control_effectiveness_id: TEXT <<ENUM(rating_value)>>
    * control_effectivenes_over_all_residual_risk_rating_id: TEXT <<ENUM(rating_value)>>
    * mitigation_further_actions: TEXT
    * control_monitor_mitigation_actions_tracking_strategy: TEXT
    * control_monitor_action_due_date: DATE
    * control_monitor_risk_owner_id: INTEGER <<FK(party)>>
    * record_status_id: TEXT <<ENUM(record_status)>>
      created_at: DATETIME
  }

  entity "incident" as incident {
    * **incident_id**: INTEGER
    --
    * title: TEXT
    * incident_date: DATE
    * time_and_time_zone: DATETIME
    * category_id: TEXT <<ENUM(incident_category_type)>>
    * severity_id: TEXT <<ENUM(severity_type)>>
    * priority_id: TEXT <<ENUM(priority_type)>>
    * internal_or_external_id: TEXT <<ENUM(incident_type)>>
    * location: TEXT
    * it_service_impacted: TEXT
    * impacted_modules: TEXT
    * impacted_dept: TEXT
    * reported_by_id: INTEGER <<FK(party)>>
    * reported_to_id: INTEGER <<FK(party)>>
    * brief_description: TEXT
    * detailed_description: TEXT
    * assigned_to_id: INTEGER <<FK(party)>>
    * assigned_date: DATE
    * investigation_details: TEXT
    * containment_details: TEXT
    * eradication_details: TEXT
    * bussiness_impact: TEXT
    * lessons_learned: TEXT
    * status_id: TEXT <<ENUM(incident_status)>>
    * closed_date: DATE
    * feedback_from_business: TEXT
    * reported_to_regulatory: TEXT
    * report_date: DATE
    * report_time: DATETIME
    * record_status_id: TEXT <<ENUM(record_status)>>
      created_at: DATETIME
  }

  boundary |o..o{ boundary
  graph |o..o{ boundary
  host |o..o{ host_boundary
  boundary |o..o{ host_boundary
  party |o..o{ person
  party |o..o{ organization
  party |o..o{ party_relation
  party |o..o{ party_relation
  party |o..o{ contact_electronics
  party |o..o{ contact_land
  party |o..o{ organization_role
  party |o..o{ organization_role
  party |o..o{ rating
  party |o..o{ contract
  party |o..o{ note
  party |o..o{ agreement
  party |o..o{ risk_register
  party |o..o{ incident
  party |o..o{ incident
  party |o..o{ incident
@enduml